# Generated by Django 4.1.7 on 2023-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_options_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
